# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'c:\Users\Batuhan Olgaç\Desktop\CovidStatus\CovidDesign.ui'
#
# Copyright ©  Maresal Programming & Batuhan Olgaç
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.setWindowModality(QtCore.Qt.WindowModal)
        MainWindow.resize(949, 757)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setSpacing(0)
        self.gridLayout.setObjectName("gridLayout")
        self.HeadBarFrame = QtWidgets.QFrame(self.centralwidget)
        self.HeadBarFrame.setMinimumSize(QtCore.QSize(50, 40))
        self.HeadBarFrame.setMaximumSize(QtCore.QSize(16777215, 40))
        self.HeadBarFrame.setStyleSheet("#HeadBarFrame {\n"
"    background-color: rgb(9, 2, 23);\n"
"}")
        self.HeadBarFrame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.HeadBarFrame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.HeadBarFrame.setObjectName("HeadBarFrame")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.HeadBarFrame)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setSpacing(5)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.IconLbl = QtWidgets.QLabel(self.HeadBarFrame)
        self.IconLbl.setMinimumSize(QtCore.QSize(50, 0))
        self.IconLbl.setMaximumSize(QtCore.QSize(50, 16777215))
        self.IconLbl.setText("")
        self.IconLbl.setObjectName("IconLbl")
        self.horizontalLayout.addWidget(self.IconLbl)
        self.NameLbl = QtWidgets.QLabel(self.HeadBarFrame)
        self.NameLbl.setStyleSheet("color:white;\n"
"font: 10pt \"Century Gothic\";")
        self.NameLbl.setAlignment(QtCore.Qt.AlignCenter)
        self.NameLbl.setObjectName("NameLbl")
        self.horizontalLayout.addWidget(self.NameLbl)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem)
        self.minimizeBtn = QtWidgets.QPushButton(self.HeadBarFrame)
        self.minimizeBtn.setMinimumSize(QtCore.QSize(15, 15))
        self.minimizeBtn.setMaximumSize(QtCore.QSize(15, 16777215))
        self.minimizeBtn.setStyleSheet("#minimizeBtn{    \n"
"    background-color: rgb(35, 143, 219);\n"
"    border-radius:1px;\n"
"}\n"
"#minimizeBtn:hover{\n"
"    \n"
"    background-color: rgb(31, 124, 191);\n"
"}\n"
"#minimizeBtn:pressed{\n"
"    \n"
"    \n"
"    background-color: rgb(41, 166, 255);\n"
"}")
        self.minimizeBtn.setText("")
        self.minimizeBtn.setObjectName("minimizeBtn")
        self.horizontalLayout.addWidget(self.minimizeBtn)
        self.FullScreenBtn = QtWidgets.QPushButton(self.HeadBarFrame)
        self.FullScreenBtn.setMinimumSize(QtCore.QSize(15, 15))
        self.FullScreenBtn.setMaximumSize(QtCore.QSize(15, 15))
        self.FullScreenBtn.setStyleSheet("#FullScreenBtn{    \n"
"    background-color: rgb(123, 214, 32);\n"
"border-radius:1px;\n"
"}\n"
"#FullScreenBtn:hover{\n"
"    background-color: rgb(107, 186, 28);\n"
"}\n"
"#FullScreenBtn:pressed{\n"
"    \n"
"    background-color: rgb(147, 255, 38);\n"
"}")
        self.FullScreenBtn.setText("")
        self.FullScreenBtn.setObjectName("FullScreenBtn")
        self.horizontalLayout.addWidget(self.FullScreenBtn)
        self.ExitBtn = QtWidgets.QPushButton(self.HeadBarFrame)
        self.ExitBtn.setMinimumSize(QtCore.QSize(15, 15))
        self.ExitBtn.setMaximumSize(QtCore.QSize(15, 15))
        self.ExitBtn.setStyleSheet("#ExitBtn{    \n"
"background-color: rgb(212, 43, 15);\n"
"border-radius:1px;\n"
"}\n"
"#ExitBtn:hover{\n"
"    background-color: rgb(181, 24, 2);\n"
"}\n"
"#ExitBtn:pressed{\n"
"    \n"
"    background-color: rgb(255, 24, 2);\n"
"}")
        self.ExitBtn.setText("")
        self.ExitBtn.setObjectName("ExitBtn")
        self.horizontalLayout.addWidget(self.ExitBtn)
        spacerItem1 = QtWidgets.QSpacerItem(10, 20, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem1)
        self.gridLayout.addWidget(self.HeadBarFrame, 0, 0, 1, 2)
        self.menuFrame = QtWidgets.QFrame(self.centralwidget)
        self.menuFrame.setMinimumSize(QtCore.QSize(50, 0))
        self.menuFrame.setMaximumSize(QtCore.QSize(200, 16777215))
        self.menuFrame.setStyleSheet("#menuFrame{\n"
"    background-color: rgb(15, 4, 38);\n"
"\n"
"}")
        self.menuFrame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.menuFrame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.menuFrame.setObjectName("menuFrame")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.menuFrame)
        self.verticalLayout.setContentsMargins(0, 10, 0, 0)
        self.verticalLayout.setSpacing(15)
        self.verticalLayout.setObjectName("verticalLayout")
        self.LogoLbl = QtWidgets.QLabel(self.menuFrame)
        self.LogoLbl.setMinimumSize(QtCore.QSize(0, 80))
        self.LogoLbl.setText("")
        self.LogoLbl.setObjectName("LogoLbl")
        self.verticalLayout.addWidget(self.LogoLbl)
        self.homeBtn = QtWidgets.QPushButton(self.menuFrame)
        self.homeBtn.setMinimumSize(QtCore.QSize(200, 50))
        self.homeBtn.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.homeBtn.setStyleSheet("#homeBtn{background-color: rgb(15, 4, 38);\n"
"color:white;\n"
"border:0px;\n"
"font: 10pt \"Century Gothic\";}\n"
"#homeBtn:Hover{\n"
"    background-color: rgb(20, 5, 51);}\n"
"#homeBtn:pressed{\n"
"    background-color: rgb(32, 9, 81);\n"
"    }")
        self.homeBtn.setObjectName("homeBtn")
        self.verticalLayout.addWidget(self.homeBtn)
        self.dunyaBtn = QtWidgets.QPushButton(self.menuFrame)
        self.dunyaBtn.setMinimumSize(QtCore.QSize(200, 50))
        self.dunyaBtn.setMaximumSize(QtCore.QSize(16777215, 16777215))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(15, 4, 38))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(15, 4, 38))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(15, 4, 38))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255, 128))
        brush.setStyle(QtCore.Qt.NoBrush)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.PlaceholderText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(15, 4, 38))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(15, 4, 38))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(15, 4, 38))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255, 128))
        brush.setStyle(QtCore.Qt.NoBrush)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.PlaceholderText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(15, 4, 38))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(15, 4, 38))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(15, 4, 38))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255, 128))
        brush.setStyle(QtCore.Qt.NoBrush)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.PlaceholderText, brush)
        self.dunyaBtn.setPalette(palette)
        self.dunyaBtn.setStyleSheet("#dunyaBtn{background-color: rgb(15, 4, 38);\n"
"color:white;\n"
"border:0px;\n"
"font: 10pt \"Century Gothic\";}\n"
"#dunyaBtn:Hover{\n"
"    background-color: rgb(20, 5, 51);}\n"
"#dunyaBtn:pressed{\n"
"    background-color: rgb(32, 9, 81);\n"
"    }")
        self.dunyaBtn.setObjectName("dunyaBtn")
        self.verticalLayout.addWidget(self.dunyaBtn)
        self.turkiyeBtn = QtWidgets.QPushButton(self.menuFrame)
        self.turkiyeBtn.setMinimumSize(QtCore.QSize(200, 50))
        self.turkiyeBtn.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.turkiyeBtn.setStyleSheet("#turkiyeBtn{background-color: rgb(15, 4, 38);\n"
"color:white;\n"
"border:0px;\n"
"font: 10pt \"Century Gothic\";}\n"
"#turkiyeBtn:Hover{\n"
"    background-color: rgb(20, 5, 51);}\n"
"#turkiyeBtn:pressed{\n"
"    background-color: rgb(32, 9, 81);\n"
"    }")
        self.turkiyeBtn.setObjectName("turkiyeBtn")
        self.verticalLayout.addWidget(self.turkiyeBtn)
        self.abdBtn = QtWidgets.QPushButton(self.menuFrame)
        self.abdBtn.setMinimumSize(QtCore.QSize(200, 50))
        self.abdBtn.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.abdBtn.setStyleSheet("#abdBtn{background-color: rgb(15, 4, 38);\n"
"color:white;\n"
"border:0px;\n"
"font: 10pt \"Century Gothic\";}\n"
"#abdBtn:Hover{\n"
"    background-color: rgb(20, 5, 51);}\n"
"#abdBtn:pressed{\n"
"    background-color: rgb(32, 9, 81);\n"
"    }")
        self.abdBtn.setObjectName("abdBtn")
        self.verticalLayout.addWidget(self.abdBtn)
        spacerItem2 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem2)
        self.settingBtn = QtWidgets.QPushButton(self.menuFrame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.settingBtn.sizePolicy().hasHeightForWidth())
        self.settingBtn.setSizePolicy(sizePolicy)
        self.settingBtn.setMinimumSize(QtCore.QSize(200, 50))
        self.settingBtn.setMaximumSize(QtCore.QSize(200, 50))
        self.settingBtn.setStyleSheet("#settingBtn{background-color: rgb(15, 4, 38);\n"
"color:white;\n"
"border:0px;\n"
"font: 10pt \"Century Gothic\";}\n"
"#settingBtn:Hover{\n"
"    background-color: rgb(20, 5, 51);}\n"
"#settingBtn:pressed{\n"
"    background-color: rgb(32, 9, 81);\n"
"    }")
        self.settingBtn.setObjectName("settingBtn")
        self.verticalLayout.addWidget(self.settingBtn)
        self.gridLayout.addWidget(self.menuFrame, 1, 0, 1, 1)
        self.PageFrame = QtWidgets.QFrame(self.centralwidget)
        self.PageFrame.setStyleSheet("#PageFrame{\n"
"        background-color: rgb(20, 5, 51);\n"
"\n"
"}")
        self.PageFrame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.PageFrame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.PageFrame.setObjectName("PageFrame")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.PageFrame)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.stackedWidget = QtWidgets.QStackedWidget(self.PageFrame)
        self.stackedWidget.setObjectName("stackedWidget")
        self.Anasayfa = QtWidgets.QWidget()
        self.Anasayfa.setObjectName("Anasayfa")
        self.bilgilendirici = QtWidgets.QPlainTextEdit(self.Anasayfa)
        self.bilgilendirici.setGeometry(QtCore.QRect(310, 20, 390, 460))
        self.bilgilendirici.setStyleSheet("background-color:transparent;\n"
"font: 10pt \"Century Gothic\";\n"
"border:none;\n"
"color:white;\n"
"")
        self.bilgilendirici.setReadOnly(True)
        self.bilgilendirici.setObjectName("bilgilendirici")
        self.GithubBtn = QtWidgets.QPushButton(self.Anasayfa)
        self.GithubBtn.setGeometry(QtCore.QRect(570, 490, 64, 64))
        self.GithubBtn.setText("")
        self.GithubBtn.setObjectName("GithubBtn")
        self.FacebookBtn = QtWidgets.QPushButton(self.Anasayfa)
        self.FacebookBtn.setGeometry(QtCore.QRect(460, 490, 64, 64))
        self.FacebookBtn.setText("")
        self.FacebookBtn.setObjectName("FacebookBtn")
        self.InstagramBtn = QtWidgets.QPushButton(self.Anasayfa)
        self.InstagramBtn.setGeometry(QtCore.QRect(350, 490, 64, 64))
        self.InstagramBtn.setText("")
        self.InstagramBtn.setObjectName("InstagramBtn")
        self.label = QtWidgets.QLabel(self.Anasayfa)
        self.label.setGeometry(QtCore.QRect(6, 90, 295, 295))
        self.label.setText("")
        self.label.setObjectName("label")
        self.GithubLbl = QtWidgets.QLabel(self.Anasayfa)
        self.GithubLbl.setGeometry(QtCore.QRect(570, 560, 64, 20))
        self.GithubLbl.setStyleSheet("font: italic 9pt \"Century Gothic\";\n"
"color:gray;")
        self.GithubLbl.setAlignment(QtCore.Qt.AlignCenter)
        self.GithubLbl.setTextInteractionFlags(QtCore.Qt.LinksAccessibleByMouse|QtCore.Qt.TextSelectableByMouse)
        self.GithubLbl.setObjectName("GithubLbl")
        self.FaceLbl = QtWidgets.QLabel(self.Anasayfa)
        self.FaceLbl.setGeometry(QtCore.QRect(427, 560, 131, 20))
        self.FaceLbl.setStyleSheet("font: italic 9pt \"Century Gothic\";\n"
"color:gray;")
        self.FaceLbl.setTextInteractionFlags(QtCore.Qt.LinksAccessibleByMouse|QtCore.Qt.TextSelectableByMouse)
        self.FaceLbl.setObjectName("FaceLbl")
        self.instaLbl = QtWidgets.QLabel(self.Anasayfa)
        self.instaLbl.setGeometry(QtCore.QRect(347, 560, 70, 20))
        self.instaLbl.setStyleSheet("font: italic 9pt \"Century Gothic\";\n"
"color:gray;")
        self.instaLbl.setAlignment(QtCore.Qt.AlignCenter)
        self.instaLbl.setTextInteractionFlags(QtCore.Qt.LinksAccessibleByMouse|QtCore.Qt.TextSelectableByMouse)
        self.instaLbl.setObjectName("instaLbl")
        self.line_2 = QtWidgets.QFrame(self.Anasayfa)
        self.line_2.setGeometry(QtCore.QRect(310, 470, 381, 16))
        self.line_2.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_2.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_2.setObjectName("line_2")
        self.stackedWidget.addWidget(self.Anasayfa)
        self.Dunya_page = QtWidgets.QWidget()
        self.Dunya_page.setObjectName("Dunya_page")
        self.line_3 = QtWidgets.QFrame(self.Dunya_page)
        self.line_3.setGeometry(QtCore.QRect(10, 310, 711, 16))
        self.line_3.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_3.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_3.setObjectName("line_3")
        self.frame_3 = QtWidgets.QFrame(self.Dunya_page)
        self.frame_3.setGeometry(QtCore.QRect(370, 30, 321, 111))
        self.frame_3.setStyleSheet("background-color: rgb(26, 26, 26);\n"
"border-radius:20px;")
        self.frame_3.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame_3.setFrameShadow(QtWidgets.QFrame.Plain)
        self.frame_3.setObjectName("frame_3")
        self.verticalLayout_7 = QtWidgets.QVBoxLayout(self.frame_3)
        self.verticalLayout_7.setObjectName("verticalLayout_7")
        self.DVefatLbl = QtWidgets.QLabel(self.frame_3)
        self.DVefatLbl.setStyleSheet("color:white;\n"
"font: 75 12pt \"Century Gothic\";")
        self.DVefatLbl.setAlignment(QtCore.Qt.AlignCenter)
        self.DVefatLbl.setObjectName("DVefatLbl")
        self.verticalLayout_7.addWidget(self.DVefatLbl)
        self.DVefatSayiLbl = QtWidgets.QLabel(self.frame_3)
        self.DVefatSayiLbl.setStyleSheet("color:white;\n"
"font: 75 15pt \"Century Gothic\";")
        self.DVefatSayiLbl.setAlignment(QtCore.Qt.AlignCenter)
        self.DVefatSayiLbl.setObjectName("DVefatSayiLbl")
        self.verticalLayout_7.addWidget(self.DVefatSayiLbl)
        self.DVefatArtisLbl = QtWidgets.QLabel(self.frame_3)
        self.DVefatArtisLbl.setStyleSheet("color:white;\n"
"font: 75 12pt \"Century Gothic\";")
        self.DVefatArtisLbl.setAlignment(QtCore.Qt.AlignCenter)
        self.DVefatArtisLbl.setObjectName("DVefatArtisLbl")
        self.verticalLayout_7.addWidget(self.DVefatArtisLbl)
        self.frame_8 = QtWidgets.QFrame(self.Dunya_page)
        self.frame_8.setGeometry(QtCore.QRect(370, 170, 321, 111))
        self.frame_8.setStyleSheet("background-color: rgb(26, 26, 26);\n"
"border-radius:20px;")
        self.frame_8.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame_8.setFrameShadow(QtWidgets.QFrame.Plain)
        self.frame_8.setObjectName("frame_8")
        self.verticalLayout_8 = QtWidgets.QVBoxLayout(self.frame_8)
        self.verticalLayout_8.setObjectName("verticalLayout_8")
        self.DAsiOlanLbl = QtWidgets.QLabel(self.frame_8)
        self.DAsiOlanLbl.setStyleSheet("color:white;\n"
"font: 75 12pt \"Century Gothic\";")
        self.DAsiOlanLbl.setAlignment(QtCore.Qt.AlignCenter)
        self.DAsiOlanLbl.setObjectName("DAsiOlanLbl")
        self.verticalLayout_8.addWidget(self.DAsiOlanLbl)
        self.DAsiOlanSayiLbl = QtWidgets.QLabel(self.frame_8)
        self.DAsiOlanSayiLbl.setStyleSheet("color:white;\n"
"font: 75 15pt \"Century Gothic\";")
        self.DAsiOlanSayiLbl.setAlignment(QtCore.Qt.AlignCenter)
        self.DAsiOlanSayiLbl.setObjectName("DAsiOlanSayiLbl")
        self.verticalLayout_8.addWidget(self.DAsiOlanSayiLbl)
        self.DAsiOlanYuzdeLbl = QtWidgets.QLabel(self.frame_8)
        self.DAsiOlanYuzdeLbl.setStyleSheet("color:white;\n"
"font: 75 12pt \"Century Gothic\";")
        self.DAsiOlanYuzdeLbl.setAlignment(QtCore.Qt.AlignCenter)
        self.DAsiOlanYuzdeLbl.setObjectName("DAsiOlanYuzdeLbl")
        self.verticalLayout_8.addWidget(self.DAsiOlanYuzdeLbl)
        self.frame_4 = QtWidgets.QFrame(self.Dunya_page)
        self.frame_4.setGeometry(QtCore.QRect(40, 30, 321, 111))
        self.frame_4.setStyleSheet("background-color: rgb(26, 26, 26);\n"
"border-radius:20px;")
        self.frame_4.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame_4.setFrameShadow(QtWidgets.QFrame.Plain)
        self.frame_4.setObjectName("frame_4")
        self.verticalLayout_9 = QtWidgets.QVBoxLayout(self.frame_4)
        self.verticalLayout_9.setObjectName("verticalLayout_9")
        self.DToplamVakaLbl = QtWidgets.QLabel(self.frame_4)
        self.DToplamVakaLbl.setStyleSheet("color:white;\n"
"font: 75 12pt \"Century Gothic\";")
        self.DToplamVakaLbl.setAlignment(QtCore.Qt.AlignCenter)
        self.DToplamVakaLbl.setObjectName("DToplamVakaLbl")
        self.verticalLayout_9.addWidget(self.DToplamVakaLbl)
        self.DToplamSayiLbl = QtWidgets.QLabel(self.frame_4)
        self.DToplamSayiLbl.setStyleSheet("color:white;\n"
"font: 75 15pt \"Century Gothic\";")
        self.DToplamSayiLbl.setAlignment(QtCore.Qt.AlignCenter)
        self.DToplamSayiLbl.setObjectName("DToplamSayiLbl")
        self.verticalLayout_9.addWidget(self.DToplamSayiLbl)
        self.DVakaArtisLbl = QtWidgets.QLabel(self.frame_4)
        self.DVakaArtisLbl.setStyleSheet("color:white;\n"
"font: 75 12pt \"Century Gothic\";")
        self.DVakaArtisLbl.setAlignment(QtCore.Qt.AlignCenter)
        self.DVakaArtisLbl.setObjectName("DVakaArtisLbl")
        self.verticalLayout_9.addWidget(self.DVakaArtisLbl)
        self.frame_9 = QtWidgets.QFrame(self.Dunya_page)
        self.frame_9.setGeometry(QtCore.QRect(40, 170, 321, 111))
        self.frame_9.setStyleSheet("background-color: rgb(26, 26, 26);\n"
"border-radius:20px;")
        self.frame_9.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame_9.setFrameShadow(QtWidgets.QFrame.Plain)
        self.frame_9.setObjectName("frame_9")
        self.verticalLayout_10 = QtWidgets.QVBoxLayout(self.frame_9)
        self.verticalLayout_10.setObjectName("verticalLayout_10")
        self.DDozLbl = QtWidgets.QLabel(self.frame_9)
        self.DDozLbl.setStyleSheet("color:white;\n"
"font: 75 12pt \"Century Gothic\";")
        self.DDozLbl.setAlignment(QtCore.Qt.AlignCenter)
        self.DDozLbl.setObjectName("DDozLbl")
        self.verticalLayout_10.addWidget(self.DDozLbl)
        self.DDozSayiLbl = QtWidgets.QLabel(self.frame_9)
        self.DDozSayiLbl.setStyleSheet("color:white;\n"
"font: 75 15pt \"Century Gothic\";")
        self.DDozSayiLbl.setAlignment(QtCore.Qt.AlignCenter)
        self.DDozSayiLbl.setObjectName("DDozSayiLbl")
        self.verticalLayout_10.addWidget(self.DDozSayiLbl)
        self.DDozArtisLbl = QtWidgets.QLabel(self.frame_9)
        self.DDozArtisLbl.setStyleSheet("color:white;\n"
"font: 75 12pt \"Century Gothic\";")
        self.DDozArtisLbl.setAlignment(QtCore.Qt.AlignCenter)
        self.DDozArtisLbl.setObjectName("DDozArtisLbl")
        self.verticalLayout_10.addWidget(self.DDozArtisLbl)
        self.ProgressBarVakaGroup_2 = QtWidgets.QGroupBox(self.Dunya_page)
        self.ProgressBarVakaGroup_2.setGeometry(QtCore.QRect(30, 340, 651, 291))
        self.ProgressBarVakaGroup_2.setStyleSheet("border:none;")
        self.ProgressBarVakaGroup_2.setTitle("")
        self.ProgressBarVakaGroup_2.setObjectName("ProgressBarVakaGroup_2")
        self.VakaPrg_4 = QtWidgets.QFrame(self.ProgressBarVakaGroup_2)
        self.VakaPrg_4.setGeometry(QtCore.QRect(60, 20, 200, 200))
        self.VakaPrg_4.setStyleSheet("#VakaPrg_4{\n"
"border-radius:100px;\n"
"background-color: rgba(255, 255, 255,120);\n"
"}")
        self.VakaPrg_4.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.VakaPrg_4.setFrameShadow(QtWidgets.QFrame.Raised)
        self.VakaPrg_4.setObjectName("VakaPrg_4")
        self.VakaPrg_5 = QtWidgets.QFrame(self.ProgressBarVakaGroup_2)
        self.VakaPrg_5.setGeometry(QtCore.QRect(70, 30, 180, 180))
        self.VakaPrg_5.setStyleSheet("QFrame{\n"
"    border-radius:90px;\n"
"\n"
"    background-color: rgb(26, 26, 26);\n"
"}")
        self.VakaPrg_5.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.VakaPrg_5.setFrameShadow(QtWidgets.QFrame.Raised)
        self.VakaPrg_5.setObjectName("VakaPrg_5")
        self.DVakaYuzdeLbl = QtWidgets.QLabel(self.VakaPrg_5)
        self.DVakaYuzdeLbl.setGeometry(QtCore.QRect(10, 60, 161, 51))
        self.DVakaYuzdeLbl.setStyleSheet("\n"
"font: 75 16pt \"Century Gothic\";\n"
"color: rgb(255, 255, 255);\n"
"")
        self.DVakaYuzdeLbl.setAlignment(QtCore.Qt.AlignCenter)
        self.DVakaYuzdeLbl.setObjectName("DVakaYuzdeLbl")
        self.VakaPrg_6 = QtWidgets.QFrame(self.ProgressBarVakaGroup_2)
        self.VakaPrg_6.setGeometry(QtCore.QRect(60, 20, 200, 200))
        self.VakaPrg_6.setStyleSheet("QFrame{\n"
"border-radius:100px;\n"
"    background-color: qconicalgradient(cx:0.5, cy:0.5, angle:90, stop:0.748 rgba(24, 175, 238, 0), stop:0.790 rgba(24, 175, 238, 255));\n"
"}")
        self.VakaPrg_6.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.VakaPrg_6.setFrameShadow(QtWidgets.QFrame.Raised)
        self.VakaPrg_6.setObjectName("VakaPrg_6")
        self.asiPrg_4 = QtWidgets.QFrame(self.ProgressBarVakaGroup_2)
        self.asiPrg_4.setGeometry(QtCore.QRect(390, 20, 200, 200))
        self.asiPrg_4.setStyleSheet("#asiPrg_4{\n"
"border-radius:100px;\n"
"background-color: rgba(255, 255, 255,120);\n"
"}")
        self.asiPrg_4.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.asiPrg_4.setFrameShadow(QtWidgets.QFrame.Raised)
        self.asiPrg_4.setObjectName("asiPrg_4")
        self.asiPrg_5 = QtWidgets.QFrame(self.ProgressBarVakaGroup_2)
        self.asiPrg_5.setGeometry(QtCore.QRect(400, 30, 180, 180))
        self.asiPrg_5.setStyleSheet("QFrame{\n"
"    border-radius:90px;\n"
"\n"
"    background-color: rgb(26, 26, 26);\n"
"}")
        self.asiPrg_5.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.asiPrg_5.setFrameShadow(QtWidgets.QFrame.Raised)
        self.asiPrg_5.setObjectName("asiPrg_5")
        self.DAsiYuzdeLbl = QtWidgets.QLabel(self.asiPrg_5)
        self.DAsiYuzdeLbl.setGeometry(QtCore.QRect(10, 60, 161, 51))
        self.DAsiYuzdeLbl.setStyleSheet("font: 75 16pt \"Century Gothic\";\n"
"color: rgb(255, 255, 255);\n"
"")
        self.DAsiYuzdeLbl.setAlignment(QtCore.Qt.AlignCenter)
        self.DAsiYuzdeLbl.setObjectName("DAsiYuzdeLbl")
        self.asiPrg_6 = QtWidgets.QFrame(self.ProgressBarVakaGroup_2)
        self.asiPrg_6.setGeometry(QtCore.QRect(390, 20, 200, 200))
        self.asiPrg_6.setStyleSheet("QFrame{\n"
"border-radius:100px;\n"
"    background-color: qconicalgradient(cx:0.5, cy:0.5, angle:90, stop:0.748 rgba(24, 175, 238, 0), stop:0.790 rgba(24, 175, 238, 255));\n"
"}")
        self.asiPrg_6.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.asiPrg_6.setFrameShadow(QtWidgets.QFrame.Raised)
        self.asiPrg_6.setObjectName("asiPrg_6")
        self.DAsiOlanSayiPrgLbl = QtWidgets.QLabel(self.ProgressBarVakaGroup_2)
        self.DAsiOlanSayiPrgLbl.setGeometry(QtCore.QRect(350, 270, 291, 20))
        self.DAsiOlanSayiPrgLbl.setStyleSheet("color:white;\n"
"font: 75 12pt \"Century Gothic\";")
        self.DAsiOlanSayiPrgLbl.setAlignment(QtCore.Qt.AlignCenter)
        self.DAsiOlanSayiPrgLbl.setObjectName("DAsiOlanSayiPrgLbl")
        self.DNufusuLbl = QtWidgets.QLabel(self.ProgressBarVakaGroup_2)
        self.DNufusuLbl.setGeometry(QtCore.QRect(40, 235, 231, 21))
        self.DNufusuLbl.setStyleSheet("color:white;\n"
"font: 75 12pt \"Century Gothic\";")
        self.DNufusuLbl.setAlignment(QtCore.Qt.AlignCenter)
        self.DNufusuLbl.setObjectName("DNufusuLbl")
        self.DNufusuLbl_2 = QtWidgets.QLabel(self.ProgressBarVakaGroup_2)
        self.DNufusuLbl_2.setGeometry(QtCore.QRect(380, 235, 231, 21))
        self.DNufusuLbl_2.setStyleSheet("color:white;\n"
"font: 75 12pt \"Century Gothic\";")
        self.DNufusuLbl_2.setAlignment(QtCore.Qt.AlignCenter)
        self.DNufusuLbl_2.setObjectName("DNufusuLbl_2")
        self.DVakaPrgLbl = QtWidgets.QLabel(self.ProgressBarVakaGroup_2)
        self.DVakaPrgLbl.setGeometry(QtCore.QRect(20, 270, 271, 20))
        self.DVakaPrgLbl.setStyleSheet("color:white;\n"
"font: 75 12pt \"Century Gothic\";")
        self.DVakaPrgLbl.setAlignment(QtCore.Qt.AlignCenter)
        self.DVakaPrgLbl.setObjectName("DVakaPrgLbl")
        self.asiPrg_4.raise_()
        self.asiPrg_6.raise_()
        self.VakaPrg_4.raise_()
        self.VakaPrg_6.raise_()
        self.VakaPrg_5.raise_()
        self.asiPrg_5.raise_()
        self.DAsiOlanSayiPrgLbl.raise_()
        self.DNufusuLbl.raise_()
        self.DNufusuLbl_2.raise_()
        self.DVakaPrgLbl.raise_()
        self.stackedWidget.addWidget(self.Dunya_page)
        self.Turkiye_page = QtWidgets.QWidget()
        self.Turkiye_page.setObjectName("Turkiye_page")
        self.frame = QtWidgets.QFrame(self.Turkiye_page)
        self.frame.setGeometry(QtCore.QRect(40, 30, 321, 111))
        self.frame.setStyleSheet("background-color: rgb(26, 26, 26);\n"
"border-radius:20px;")
        self.frame.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame.setFrameShadow(QtWidgets.QFrame.Plain)
        self.frame.setObjectName("frame")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.frame)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.TToplamVakaLbl = QtWidgets.QLabel(self.frame)
        self.TToplamVakaLbl.setStyleSheet("color:white;\n"
"font: 75 12pt \"Century Gothic\";")
        self.TToplamVakaLbl.setAlignment(QtCore.Qt.AlignCenter)
        self.TToplamVakaLbl.setObjectName("TToplamVakaLbl")
        self.verticalLayout_3.addWidget(self.TToplamVakaLbl)
        self.TToplamSayiLbl = QtWidgets.QLabel(self.frame)
        self.TToplamSayiLbl.setStyleSheet("color:white;\n"
"font: 75 15pt \"Century Gothic\";")
        self.TToplamSayiLbl.setAlignment(QtCore.Qt.AlignCenter)
        self.TToplamSayiLbl.setObjectName("TToplamSayiLbl")
        self.verticalLayout_3.addWidget(self.TToplamSayiLbl)
        self.TVakaArtisLbl = QtWidgets.QLabel(self.frame)
        self.TVakaArtisLbl.setStyleSheet("color:white;\n"
"font: 75 12pt \"Century Gothic\";")
        self.TVakaArtisLbl.setAlignment(QtCore.Qt.AlignCenter)
        self.TVakaArtisLbl.setObjectName("TVakaArtisLbl")
        self.verticalLayout_3.addWidget(self.TVakaArtisLbl)
        self.frame_2 = QtWidgets.QFrame(self.Turkiye_page)
        self.frame_2.setGeometry(QtCore.QRect(370, 30, 321, 111))
        self.frame_2.setStyleSheet("background-color: rgb(26, 26, 26);\n"
"border-radius:20px;")
        self.frame_2.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Plain)
        self.frame_2.setObjectName("frame_2")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.frame_2)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.TVefatLbl = QtWidgets.QLabel(self.frame_2)
        self.TVefatLbl.setStyleSheet("color:white;\n"
"font: 75 12pt \"Century Gothic\";")
        self.TVefatLbl.setAlignment(QtCore.Qt.AlignCenter)
        self.TVefatLbl.setObjectName("TVefatLbl")
        self.verticalLayout_4.addWidget(self.TVefatLbl)
        self.TVefatSayiLbl = QtWidgets.QLabel(self.frame_2)
        self.TVefatSayiLbl.setStyleSheet("color:white;\n"
"font: 75 15pt \"Century Gothic\";")
        self.TVefatSayiLbl.setAlignment(QtCore.Qt.AlignCenter)
        self.TVefatSayiLbl.setObjectName("TVefatSayiLbl")
        self.verticalLayout_4.addWidget(self.TVefatSayiLbl)
        self.TVefatArtisLbl = QtWidgets.QLabel(self.frame_2)
        self.TVefatArtisLbl.setStyleSheet("color:white;\n"
"font: 75 12pt \"Century Gothic\";")
        self.TVefatArtisLbl.setAlignment(QtCore.Qt.AlignCenter)
        self.TVefatArtisLbl.setObjectName("TVefatArtisLbl")
        self.verticalLayout_4.addWidget(self.TVefatArtisLbl)
        self.frame_5 = QtWidgets.QFrame(self.Turkiye_page)
        self.frame_5.setGeometry(QtCore.QRect(40, 170, 321, 111))
        self.frame_5.setStyleSheet("background-color: rgb(26, 26, 26);\n"
"border-radius:20px;")
        self.frame_5.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame_5.setFrameShadow(QtWidgets.QFrame.Plain)
        self.frame_5.setObjectName("frame_5")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout(self.frame_5)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.TDozLbl = QtWidgets.QLabel(self.frame_5)
        self.TDozLbl.setStyleSheet("color:white;\n"
"font: 75 12pt \"Century Gothic\";")
        self.TDozLbl.setAlignment(QtCore.Qt.AlignCenter)
        self.TDozLbl.setObjectName("TDozLbl")
        self.verticalLayout_5.addWidget(self.TDozLbl)
        self.TDozSayiLbl = QtWidgets.QLabel(self.frame_5)
        self.TDozSayiLbl.setStyleSheet("color:white;\n"
"font: 75 15pt \"Century Gothic\";")
        self.TDozSayiLbl.setAlignment(QtCore.Qt.AlignCenter)
        self.TDozSayiLbl.setObjectName("TDozSayiLbl")
        self.verticalLayout_5.addWidget(self.TDozSayiLbl)
        self.TDozArtisLbl = QtWidgets.QLabel(self.frame_5)
        self.TDozArtisLbl.setStyleSheet("color:white;\n"
"font: 75 12pt \"Century Gothic\";")
        self.TDozArtisLbl.setAlignment(QtCore.Qt.AlignCenter)
        self.TDozArtisLbl.setObjectName("TDozArtisLbl")
        self.verticalLayout_5.addWidget(self.TDozArtisLbl)
        self.frame_6 = QtWidgets.QFrame(self.Turkiye_page)
        self.frame_6.setGeometry(QtCore.QRect(370, 170, 321, 111))
        self.frame_6.setStyleSheet("background-color: rgb(26, 26, 26);\n"
"border-radius:20px;")
        self.frame_6.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame_6.setFrameShadow(QtWidgets.QFrame.Plain)
        self.frame_6.setObjectName("frame_6")
        self.verticalLayout_6 = QtWidgets.QVBoxLayout(self.frame_6)
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.TAsiOlanLbl = QtWidgets.QLabel(self.frame_6)
        self.TAsiOlanLbl.setStyleSheet("color:white;\n"
"font: 75 12pt \"Century Gothic\";")
        self.TAsiOlanLbl.setAlignment(QtCore.Qt.AlignCenter)
        self.TAsiOlanLbl.setObjectName("TAsiOlanLbl")
        self.verticalLayout_6.addWidget(self.TAsiOlanLbl)
        self.TAsiOlanSayiLbl = QtWidgets.QLabel(self.frame_6)
        self.TAsiOlanSayiLbl.setStyleSheet("color:white;\n"
"font: 75 15pt \"Century Gothic\";")
        self.TAsiOlanSayiLbl.setAlignment(QtCore.Qt.AlignCenter)
        self.TAsiOlanSayiLbl.setObjectName("TAsiOlanSayiLbl")
        self.verticalLayout_6.addWidget(self.TAsiOlanSayiLbl)
        self.TAsiOlanYuzdeLbl = QtWidgets.QLabel(self.frame_6)
        self.TAsiOlanYuzdeLbl.setStyleSheet("color:white;\n"
"font: 75 12pt \"Century Gothic\";")
        self.TAsiOlanYuzdeLbl.setAlignment(QtCore.Qt.AlignCenter)
        self.TAsiOlanYuzdeLbl.setObjectName("TAsiOlanYuzdeLbl")
        self.verticalLayout_6.addWidget(self.TAsiOlanYuzdeLbl)
        self.line = QtWidgets.QFrame(self.Turkiye_page)
        self.line.setGeometry(QtCore.QRect(10, 310, 711, 16))
        self.line.setFrameShape(QtWidgets.QFrame.HLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.ProgressBarVakaGroup = QtWidgets.QGroupBox(self.Turkiye_page)
        self.ProgressBarVakaGroup.setGeometry(QtCore.QRect(30, 340, 651, 291))
        self.ProgressBarVakaGroup.setStyleSheet("#ProgressBarVakaGroup{\n"
"border:none;}")
        self.ProgressBarVakaGroup.setTitle("")
        self.ProgressBarVakaGroup.setObjectName("ProgressBarVakaGroup")
        self.VakaPrg_2 = QtWidgets.QFrame(self.ProgressBarVakaGroup)
        self.VakaPrg_2.setGeometry(QtCore.QRect(60, 20, 200, 200))
        self.VakaPrg_2.setStyleSheet("#VakaPrg_2{\n"
"border-radius:100px;\n"
"background-color: rgba(255, 255, 255,120);\n"
"}")
        self.VakaPrg_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.VakaPrg_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.VakaPrg_2.setObjectName("VakaPrg_2")
        self.VakaPrg_3 = QtWidgets.QFrame(self.ProgressBarVakaGroup)
        self.VakaPrg_3.setGeometry(QtCore.QRect(70, 30, 180, 180))
        self.VakaPrg_3.setStyleSheet("QFrame{\n"
"    border-radius:90px;\n"
"\n"
"    background-color: rgb(26, 26, 26);\n"
"}")
        self.VakaPrg_3.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.VakaPrg_3.setFrameShadow(QtWidgets.QFrame.Raised)
        self.VakaPrg_3.setObjectName("VakaPrg_3")
        self.TVakaYuzdeLbl = QtWidgets.QLabel(self.VakaPrg_3)
        self.TVakaYuzdeLbl.setGeometry(QtCore.QRect(10, 60, 161, 51))
        self.TVakaYuzdeLbl.setStyleSheet("\n"
"font: 75 16pt \"Century Gothic\";\n"
"color: rgb(255, 255, 255);\n"
"")
        self.TVakaYuzdeLbl.setAlignment(QtCore.Qt.AlignCenter)
        self.TVakaYuzdeLbl.setObjectName("TVakaYuzdeLbl")
        self.VakaPrg = QtWidgets.QFrame(self.ProgressBarVakaGroup)
        self.VakaPrg.setGeometry(QtCore.QRect(60, 20, 200, 200))
        self.VakaPrg.setStyleSheet("QFrame{\n"
"border-radius:100px;\n"
"    background-color: qconicalgradient(cx:0.5, cy:0.5, angle:90, stop:0.748 rgba(24, 175, 238, 0), stop:0.790 rgba(24, 175, 238, 255));\n"
"}")
        self.VakaPrg.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.VakaPrg.setFrameShadow(QtWidgets.QFrame.Raised)
        self.VakaPrg.setObjectName("VakaPrg")
        self.asiPrg_3 = QtWidgets.QFrame(self.ProgressBarVakaGroup)
        self.asiPrg_3.setGeometry(QtCore.QRect(390, 20, 200, 200))
        self.asiPrg_3.setStyleSheet("#asiPrg_3{\n"
"border-radius:100px;\n"
"background-color: rgba(255, 255, 255,120);\n"
"}")
        self.asiPrg_3.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.asiPrg_3.setFrameShadow(QtWidgets.QFrame.Raised)
        self.asiPrg_3.setObjectName("asiPrg_3")
        self.asiPrg_2 = QtWidgets.QFrame(self.ProgressBarVakaGroup)
        self.asiPrg_2.setGeometry(QtCore.QRect(400, 30, 180, 180))
        self.asiPrg_2.setStyleSheet("QFrame{\n"
"    border-radius:90px;\n"
"\n"
"    background-color: rgb(26, 26, 26);\n"
"}")
        self.asiPrg_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.asiPrg_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.asiPrg_2.setObjectName("asiPrg_2")
        self.TAsiYuzdeLbl = QtWidgets.QLabel(self.asiPrg_2)
        self.TAsiYuzdeLbl.setGeometry(QtCore.QRect(10, 60, 161, 51))
        self.TAsiYuzdeLbl.setStyleSheet("\n"
"font: 75 16pt \"Century Gothic\";\n"
"color: rgb(255, 255, 255);\n"
"")
        self.TAsiYuzdeLbl.setAlignment(QtCore.Qt.AlignCenter)
        self.TAsiYuzdeLbl.setObjectName("TAsiYuzdeLbl")
        self.asiPrg = QtWidgets.QFrame(self.ProgressBarVakaGroup)
        self.asiPrg.setGeometry(QtCore.QRect(390, 20, 200, 200))
        self.asiPrg.setStyleSheet("QFrame{\n"
"border-radius:100px;\n"
"    background-color: qconicalgradient(cx:0.5, cy:0.5, angle:90, stop:0.748 rgba(24, 175, 238, 0), stop:0.790 rgba(24, 175, 238, 255));\n"
"}")
        self.asiPrg.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.asiPrg.setFrameShadow(QtWidgets.QFrame.Raised)
        self.asiPrg.setObjectName("asiPrg")
        self.TAsiOlanSayiPrgLbl = QtWidgets.QLabel(self.ProgressBarVakaGroup)
        self.TAsiOlanSayiPrgLbl.setGeometry(QtCore.QRect(350, 270, 291, 20))
        self.TAsiOlanSayiPrgLbl.setStyleSheet("color:white;\n"
"font: 75 12pt \"Century Gothic\";")
        self.TAsiOlanSayiPrgLbl.setAlignment(QtCore.Qt.AlignCenter)
        self.TAsiOlanSayiPrgLbl.setObjectName("TAsiOlanSayiPrgLbl")
        self.TNufusuLbl_2 = QtWidgets.QLabel(self.ProgressBarVakaGroup)
        self.TNufusuLbl_2.setGeometry(QtCore.QRect(55, 235, 201, 21))
        self.TNufusuLbl_2.setStyleSheet("color:white;\n"
"font: 75 12pt \"Century Gothic\";")
        self.TNufusuLbl_2.setAlignment(QtCore.Qt.AlignCenter)
        self.TNufusuLbl_2.setObjectName("TNufusuLbl_2")
        self.TNufusuLbl = QtWidgets.QLabel(self.ProgressBarVakaGroup)
        self.TNufusuLbl.setGeometry(QtCore.QRect(390, 235, 201, 21))
        self.TNufusuLbl.setStyleSheet("color:white;\n"
"font: 75 12pt \"Century Gothic\";")
        self.TNufusuLbl.setAlignment(QtCore.Qt.AlignCenter)
        self.TNufusuLbl.setObjectName("TNufusuLbl")
        self.TVakaPrgLbl = QtWidgets.QLabel(self.ProgressBarVakaGroup)
        self.TVakaPrgLbl.setGeometry(QtCore.QRect(20, 270, 271, 20))
        self.TVakaPrgLbl.setStyleSheet("color:white;\n"
"font: 75 12pt \"Century Gothic\";")
        self.TVakaPrgLbl.setAlignment(QtCore.Qt.AlignCenter)
        self.TVakaPrgLbl.setObjectName("TVakaPrgLbl")
        self.asiPrg_3.raise_()
        self.asiPrg.raise_()
        self.VakaPrg_2.raise_()
        self.VakaPrg.raise_()
        self.VakaPrg_3.raise_()
        self.asiPrg_2.raise_()
        self.TAsiOlanSayiPrgLbl.raise_()
        self.TNufusuLbl_2.raise_()
        self.TNufusuLbl.raise_()
        self.TVakaPrgLbl.raise_()
        self.stackedWidget.addWidget(self.Turkiye_page)
        self.ABD_page = QtWidgets.QWidget()
        self.ABD_page.setObjectName("ABD_page")
        self.frame_10 = QtWidgets.QFrame(self.ABD_page)
        self.frame_10.setGeometry(QtCore.QRect(370, 170, 321, 111))
        self.frame_10.setStyleSheet("background-color: rgb(26, 26, 26);\n"
"border-radius:20px;")
        self.frame_10.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame_10.setFrameShadow(QtWidgets.QFrame.Plain)
        self.frame_10.setObjectName("frame_10")
        self.verticalLayout_15 = QtWidgets.QVBoxLayout(self.frame_10)
        self.verticalLayout_15.setObjectName("verticalLayout_15")
        self.AAsiOlanLbl = QtWidgets.QLabel(self.frame_10)
        self.AAsiOlanLbl.setStyleSheet("color:white;\n"
"font: 75 12pt \"Century Gothic\";")
        self.AAsiOlanLbl.setAlignment(QtCore.Qt.AlignCenter)
        self.AAsiOlanLbl.setObjectName("AAsiOlanLbl")
        self.verticalLayout_15.addWidget(self.AAsiOlanLbl)
        self.AAsiOlanSayiLbl = QtWidgets.QLabel(self.frame_10)
        self.AAsiOlanSayiLbl.setStyleSheet("color:white;\n"
"font: 75 15pt \"Century Gothic\";")
        self.AAsiOlanSayiLbl.setAlignment(QtCore.Qt.AlignCenter)
        self.AAsiOlanSayiLbl.setObjectName("AAsiOlanSayiLbl")
        self.verticalLayout_15.addWidget(self.AAsiOlanSayiLbl)
        self.AAsiOlanYuzdeLbl = QtWidgets.QLabel(self.frame_10)
        self.AAsiOlanYuzdeLbl.setStyleSheet("color:white;\n"
"font: 75 12pt \"Century Gothic\";")
        self.AAsiOlanYuzdeLbl.setAlignment(QtCore.Qt.AlignCenter)
        self.AAsiOlanYuzdeLbl.setObjectName("AAsiOlanYuzdeLbl")
        self.verticalLayout_15.addWidget(self.AAsiOlanYuzdeLbl)
        self.line_4 = QtWidgets.QFrame(self.ABD_page)
        self.line_4.setGeometry(QtCore.QRect(10, 310, 711, 16))
        self.line_4.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_4.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_4.setObjectName("line_4")
        self.frame_11 = QtWidgets.QFrame(self.ABD_page)
        self.frame_11.setGeometry(QtCore.QRect(370, 30, 321, 111))
        self.frame_11.setStyleSheet("background-color: rgb(26, 26, 26);\n"
"border-radius:20px;")
        self.frame_11.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame_11.setFrameShadow(QtWidgets.QFrame.Plain)
        self.frame_11.setObjectName("frame_11")
        self.verticalLayout_16 = QtWidgets.QVBoxLayout(self.frame_11)
        self.verticalLayout_16.setObjectName("verticalLayout_16")
        self.AVefatLbl = QtWidgets.QLabel(self.frame_11)
        self.AVefatLbl.setStyleSheet("color:white;\n"
"font: 75 12pt \"Century Gothic\";")
        self.AVefatLbl.setAlignment(QtCore.Qt.AlignCenter)
        self.AVefatLbl.setObjectName("AVefatLbl")
        self.verticalLayout_16.addWidget(self.AVefatLbl)
        self.AVefatSayiLbl = QtWidgets.QLabel(self.frame_11)
        self.AVefatSayiLbl.setStyleSheet("color:white;\n"
"font: 75 15pt \"Century Gothic\";")
        self.AVefatSayiLbl.setAlignment(QtCore.Qt.AlignCenter)
        self.AVefatSayiLbl.setObjectName("AVefatSayiLbl")
        self.verticalLayout_16.addWidget(self.AVefatSayiLbl)
        self.AVefatArtisLbl = QtWidgets.QLabel(self.frame_11)
        self.AVefatArtisLbl.setStyleSheet("color:white;\n"
"font: 75 12pt \"Century Gothic\";")
        self.AVefatArtisLbl.setAlignment(QtCore.Qt.AlignCenter)
        self.AVefatArtisLbl.setObjectName("AVefatArtisLbl")
        self.verticalLayout_16.addWidget(self.AVefatArtisLbl)
        self.ProgressBarVakaGroup_3 = QtWidgets.QGroupBox(self.ABD_page)
        self.ProgressBarVakaGroup_3.setGeometry(QtCore.QRect(30, 340, 651, 291))
        self.ProgressBarVakaGroup_3.setStyleSheet("border:none;")
        self.ProgressBarVakaGroup_3.setTitle("")
        self.ProgressBarVakaGroup_3.setObjectName("ProgressBarVakaGroup_3")
        self.VakaPrg_10 = QtWidgets.QFrame(self.ProgressBarVakaGroup_3)
        self.VakaPrg_10.setGeometry(QtCore.QRect(60, 20, 200, 200))
        self.VakaPrg_10.setStyleSheet("#VakaPrg_10{\n"
"border-radius:100px;\n"
"background-color: rgba(255, 255, 255,120);\n"
"}")
        self.VakaPrg_10.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.VakaPrg_10.setFrameShadow(QtWidgets.QFrame.Raised)
        self.VakaPrg_10.setObjectName("VakaPrg_10")
        self.VakaPrg_11 = QtWidgets.QFrame(self.ProgressBarVakaGroup_3)
        self.VakaPrg_11.setGeometry(QtCore.QRect(70, 30, 180, 180))
        self.VakaPrg_11.setStyleSheet("QFrame{\n"
"    border-radius:90px;\n"
"    background-color: rgb(26, 26, 26);\n"
"}")
        self.VakaPrg_11.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.VakaPrg_11.setFrameShadow(QtWidgets.QFrame.Raised)
        self.VakaPrg_11.setObjectName("VakaPrg_11")
        self.AVakaYuzdeLbl = QtWidgets.QLabel(self.VakaPrg_11)
        self.AVakaYuzdeLbl.setGeometry(QtCore.QRect(10, 60, 161, 51))
        self.AVakaYuzdeLbl.setStyleSheet("\n"
"font: 75 16pt \"Century Gothic\";\n"
"color: rgb(255, 255, 255);\n"
"")
        self.AVakaYuzdeLbl.setAlignment(QtCore.Qt.AlignCenter)
        self.AVakaYuzdeLbl.setObjectName("AVakaYuzdeLbl")
        self.VakaPrg_12 = QtWidgets.QFrame(self.ProgressBarVakaGroup_3)
        self.VakaPrg_12.setGeometry(QtCore.QRect(60, 20, 200, 200))
        self.VakaPrg_12.setStyleSheet("QFrame{\n"
"border-radius:100px;\n"
"    background-color: qconicalgradient(cx:0.5, cy:0.5, angle:90, stop:0.748 rgba(24, 175, 238, 0), stop:0.790 rgba(24, 175, 238, 255));\n"
"}")
        self.VakaPrg_12.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.VakaPrg_12.setFrameShadow(QtWidgets.QFrame.Raised)
        self.VakaPrg_12.setObjectName("VakaPrg_12")
        self.asiPrg_10 = QtWidgets.QFrame(self.ProgressBarVakaGroup_3)
        self.asiPrg_10.setGeometry(QtCore.QRect(390, 20, 200, 200))
        self.asiPrg_10.setStyleSheet("#asiPrg_10{\n"
"border-radius:100px;\n"
"background-color: rgba(255, 255, 255,120);\n"
"}")
        self.asiPrg_10.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.asiPrg_10.setFrameShadow(QtWidgets.QFrame.Raised)
        self.asiPrg_10.setObjectName("asiPrg_10")
        self.asiPrg_11 = QtWidgets.QFrame(self.ProgressBarVakaGroup_3)
        self.asiPrg_11.setGeometry(QtCore.QRect(400, 30, 180, 180))
        self.asiPrg_11.setStyleSheet("QFrame{\n"
"    border-radius:90px;\n"
"\n"
"    background-color: rgb(26, 26, 26);\n"
"}")
        self.asiPrg_11.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.asiPrg_11.setFrameShadow(QtWidgets.QFrame.Raised)
        self.asiPrg_11.setObjectName("asiPrg_11")
        self.AAsiYuzdeLbl = QtWidgets.QLabel(self.asiPrg_11)
        self.AAsiYuzdeLbl.setGeometry(QtCore.QRect(10, 60, 161, 51))
        self.AAsiYuzdeLbl.setStyleSheet("font: 75 16pt \"Century Gothic\";\n"
"color: rgb(255, 255, 255);\n"
"")
        self.AAsiYuzdeLbl.setAlignment(QtCore.Qt.AlignCenter)
        self.AAsiYuzdeLbl.setObjectName("AAsiYuzdeLbl")
        self.asiPrg_12 = QtWidgets.QFrame(self.ProgressBarVakaGroup_3)
        self.asiPrg_12.setGeometry(QtCore.QRect(390, 20, 200, 200))
        self.asiPrg_12.setStyleSheet("QFrame{\n"
"border-radius:100px;\n"
"    background-color: qconicalgradient(cx:0.5, cy:0.5, angle:90, stop:0.748 rgba(24, 175, 238, 0), stop:0.790 rgba(24, 175, 238, 255));\n"
"}")
        self.asiPrg_12.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.asiPrg_12.setFrameShadow(QtWidgets.QFrame.Raised)
        self.asiPrg_12.setObjectName("asiPrg_12")
        self.AAsiOlanSayiPrgLbl = QtWidgets.QLabel(self.ProgressBarVakaGroup_3)
        self.AAsiOlanSayiPrgLbl.setGeometry(QtCore.QRect(350, 270, 291, 20))
        self.AAsiOlanSayiPrgLbl.setStyleSheet("color:white;\n"
"font: 75 12pt \"Century Gothic\";")
        self.AAsiOlanSayiPrgLbl.setAlignment(QtCore.Qt.AlignCenter)
        self.AAsiOlanSayiPrgLbl.setObjectName("AAsiOlanSayiPrgLbl")
        self.ANufusLbl = QtWidgets.QLabel(self.ProgressBarVakaGroup_3)
        self.ANufusLbl.setGeometry(QtCore.QRect(55, 235, 201, 21))
        self.ANufusLbl.setStyleSheet("color:white;\n"
"font: 75 12pt \"Century Gothic\";")
        self.ANufusLbl.setAlignment(QtCore.Qt.AlignCenter)
        self.ANufusLbl.setObjectName("ANufusLbl")
        self.ANufusLbl_2 = QtWidgets.QLabel(self.ProgressBarVakaGroup_3)
        self.ANufusLbl_2.setGeometry(QtCore.QRect(390, 235, 201, 21))
        self.ANufusLbl_2.setStyleSheet("color:white;\n"
"font: 75 12pt \"Century Gothic\";")
        self.ANufusLbl_2.setAlignment(QtCore.Qt.AlignCenter)
        self.ANufusLbl_2.setObjectName("ANufusLbl_2")
        self.AToplamVakaPrgLbl = QtWidgets.QLabel(self.ProgressBarVakaGroup_3)
        self.AToplamVakaPrgLbl.setGeometry(QtCore.QRect(20, 270, 271, 20))
        self.AToplamVakaPrgLbl.setStyleSheet("color:white;\n"
"font: 75 12pt \"Century Gothic\";")
        self.AToplamVakaPrgLbl.setAlignment(QtCore.Qt.AlignCenter)
        self.AToplamVakaPrgLbl.setObjectName("AToplamVakaPrgLbl")
        self.asiPrg_10.raise_()
        self.asiPrg_12.raise_()
        self.VakaPrg_10.raise_()
        self.VakaPrg_12.raise_()
        self.asiPrg_11.raise_()
        self.AAsiOlanSayiPrgLbl.raise_()
        self.ANufusLbl.raise_()
        self.ANufusLbl_2.raise_()
        self.AToplamVakaPrgLbl.raise_()
        self.VakaPrg_11.raise_()
        self.frame_12 = QtWidgets.QFrame(self.ABD_page)
        self.frame_12.setGeometry(QtCore.QRect(40, 170, 321, 111))
        self.frame_12.setStyleSheet("background-color: rgb(26, 26, 26);\n"
"border-radius:20px;")
        self.frame_12.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame_12.setFrameShadow(QtWidgets.QFrame.Plain)
        self.frame_12.setObjectName("frame_12")
        self.verticalLayout_17 = QtWidgets.QVBoxLayout(self.frame_12)
        self.verticalLayout_17.setObjectName("verticalLayout_17")
        self.ADozLbl = QtWidgets.QLabel(self.frame_12)
        self.ADozLbl.setStyleSheet("color:white;\n"
"font: 75 12pt \"Century Gothic\";")
        self.ADozLbl.setAlignment(QtCore.Qt.AlignCenter)
        self.ADozLbl.setObjectName("ADozLbl")
        self.verticalLayout_17.addWidget(self.ADozLbl)
        self.ADozSayiLbl = QtWidgets.QLabel(self.frame_12)
        self.ADozSayiLbl.setStyleSheet("color:white;\n"
"font: 75 15pt \"Century Gothic\";")
        self.ADozSayiLbl.setAlignment(QtCore.Qt.AlignCenter)
        self.ADozSayiLbl.setObjectName("ADozSayiLbl")
        self.verticalLayout_17.addWidget(self.ADozSayiLbl)
        self.ADozArtisLbl = QtWidgets.QLabel(self.frame_12)
        self.ADozArtisLbl.setStyleSheet("color:white;\n"
"font: 75 12pt \"Century Gothic\";")
        self.ADozArtisLbl.setAlignment(QtCore.Qt.AlignCenter)
        self.ADozArtisLbl.setObjectName("ADozArtisLbl")
        self.verticalLayout_17.addWidget(self.ADozArtisLbl)
        self.frame_13 = QtWidgets.QFrame(self.ABD_page)
        self.frame_13.setGeometry(QtCore.QRect(40, 30, 321, 111))
        self.frame_13.setStyleSheet("background-color: rgb(26, 26, 26);\n"
"border-radius:20px;")
        self.frame_13.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame_13.setFrameShadow(QtWidgets.QFrame.Plain)
        self.frame_13.setObjectName("frame_13")
        self.verticalLayout_18 = QtWidgets.QVBoxLayout(self.frame_13)
        self.verticalLayout_18.setObjectName("verticalLayout_18")
        self.AToplamVakaLbl = QtWidgets.QLabel(self.frame_13)
        self.AToplamVakaLbl.setStyleSheet("color:white;\n"
"font: 75 12pt \"Century Gothic\";")
        self.AToplamVakaLbl.setAlignment(QtCore.Qt.AlignCenter)
        self.AToplamVakaLbl.setObjectName("AToplamVakaLbl")
        self.verticalLayout_18.addWidget(self.AToplamVakaLbl)
        self.AToplamSayiLbl = QtWidgets.QLabel(self.frame_13)
        self.AToplamSayiLbl.setStyleSheet("color:white;\n"
"font: 75 15pt \"Century Gothic\";")
        self.AToplamSayiLbl.setAlignment(QtCore.Qt.AlignCenter)
        self.AToplamSayiLbl.setObjectName("AToplamSayiLbl")
        self.verticalLayout_18.addWidget(self.AToplamSayiLbl)
        self.AVakaArtisLbl = QtWidgets.QLabel(self.frame_13)
        self.AVakaArtisLbl.setStyleSheet("color:white;\n"
"font: 75 12pt \"Century Gothic\";")
        self.AVakaArtisLbl.setAlignment(QtCore.Qt.AlignCenter)
        self.AVakaArtisLbl.setObjectName("AVakaArtisLbl")
        self.verticalLayout_18.addWidget(self.AVakaArtisLbl)
        self.stackedWidget.addWidget(self.ABD_page)
        self.verticalLayout_2.addWidget(self.stackedWidget)
        self.copyright = QtWidgets.QLabel(self.PageFrame)
        self.copyright.setStyleSheet("#copyright{\n"
"    font: 75 italic 10pt \"Century Gothic\";\n"
"color: rgb(68, 222, 44);\n"
"}")
        self.copyright.setAlignment(QtCore.Qt.AlignCenter)
        self.copyright.setObjectName("copyright")
        self.verticalLayout_2.addWidget(self.copyright)
        self.gridLayout.addWidget(self.PageFrame, 1, 1, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 949, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)

        self.retranslateUi(MainWindow)
        self.stackedWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.NameLbl.setText(_translate("MainWindow", "Koronavirüs Takip | Maresal PRM"))
        self.homeBtn.setText(_translate("MainWindow", "Anasayfa"))
        self.dunyaBtn.setText(_translate("MainWindow", "Dünya"))
        self.turkiyeBtn.setText(_translate("MainWindow", "Türkiye"))
        self.abdBtn.setText(_translate("MainWindow", "ABD"))
        self.settingBtn.setText(_translate("MainWindow", "Ayarlar"))
        self.bilgilendirici.setPlainText(_translate("MainWindow", "Koronavirüs hastalığı (COVID-19), yeni keşfedilen bir koronavirüsün neden olduğu bulaşıcı hastalıktır.\n"
"\n"
"COVID-19\'a yakalanan çoğu kişi, hafif ila orta düzeyde semptomlar göstermekte ve özel bir tedaviye ihtiyaç duymadan iyileşmektedir.\n"
"\n"
"____________________________________________________\n"
"\n"
"NASIL YAYILIR?\n"
"\n"
"COVID-19\'a neden olan virüs, genellikle enfekte kişinin öksürmesi, hapşırması veya nefes vermesi sonucu oluşan damlacıklar yoluyla bulaşır. Bu damlacıklar çok ağır olduğundan havada asılı kalamaz ve hemen yere ya da yüzeylere düşer.\n"
"\n"
"COVID-19 ile enfekte birinin yakınındayken virüsü solursanız veya virüsün bulaştığı bir yüzeye dokunduktan sonra gözlerinize, burnunuza veya ağzınıza dokunursanız enfekte olabilirsiniz.\n"
"\n"
"Programımızda kullandığımız covid19 verilerini tümü https://news.google.com/covid19 adresinden alınmıştır.\n"
"\n"
"Programın tüm tasarımı Maresal Programming\'e aittir."))
        self.GithubLbl.setText(_translate("MainWindow", "IMaresaLI"))
        self.FaceLbl.setText(_translate("MainWindow", "maresalprogramming"))
        self.instaLbl.setText(_translate("MainWindow", "@maresalp"))
        self.DVefatLbl.setText(_translate("MainWindow", "Vefat Sayısı"))
        self.DVefatSayiLbl.setText(_translate("MainWindow", "33.454"))
        self.DVefatArtisLbl.setText(_translate("MainWindow", "Dün bildirilen vefat sayısı : + 253"))
        self.DAsiOlanLbl.setText(_translate("MainWindow", "Tüm Aşıları Tamamlanan Kişi Sayısı"))
        self.DAsiOlanSayiLbl.setText(_translate("MainWindow", "7.542.933"))
        self.DAsiOlanYuzdeLbl.setText(_translate("MainWindow", "Nüfus yüzdesi : %9"))
        self.DToplamVakaLbl.setText(_translate("MainWindow", "Toplam Vaka Sayısı "))
        self.DToplamSayiLbl.setText(_translate("MainWindow", "3.745.657"))
        self.DVakaArtisLbl.setText(_translate("MainWindow", "Dün bildirilen Vaka sayısı  : + 55.791"))
        self.DDozLbl.setText(_translate("MainWindow", "Toplam Doz Sayısı"))
        self.DDozSayiLbl.setText(_translate("MainWindow", "18.320.384"))
        self.DDozArtisLbl.setText(_translate("MainWindow", "Dün bildirilen doz sayısı  : + 230.601"))
        self.DVakaYuzdeLbl.setText(_translate("MainWindow", "25 %"))
        self.DAsiYuzdeLbl.setText(_translate("MainWindow", "25 %"))
        self.DAsiOlanSayiPrgLbl.setText(_translate("MainWindow", "Toplam Aşı Olan Sayısı : 3.745.657"))
        self.DNufusuLbl.setText(_translate("MainWindow", "Dünya Nüfusu : 7.859.092.000"))
        self.DNufusuLbl_2.setText(_translate("MainWindow", "Dünya Nüfusu : 7.859.092.000"))
        self.DVakaPrgLbl.setText(_translate("MainWindow", "Toplam Vaka Sayısı : 3.745.657"))
        self.TToplamVakaLbl.setText(_translate("MainWindow", "Toplam Vaka Sayısı "))
        self.TToplamSayiLbl.setText(_translate("MainWindow", "3.745.657"))
        self.TVakaArtisLbl.setText(_translate("MainWindow", "Dün bildirilen Vaka sayısı  : + 55.791"))
        self.TVefatLbl.setText(_translate("MainWindow", "Vefat Sayısı"))
        self.TVefatSayiLbl.setText(_translate("MainWindow", "33.454"))
        self.TVefatArtisLbl.setText(_translate("MainWindow", "Dün bildirilen vefat sayısı : + 253"))
        self.TDozLbl.setText(_translate("MainWindow", "Toplam Doz Sayısı"))
        self.TDozSayiLbl.setText(_translate("MainWindow", "18.320.384"))
        self.TDozArtisLbl.setText(_translate("MainWindow", "Dün bildirilen doz sayısı  : + 230.601"))
        self.TAsiOlanLbl.setText(_translate("MainWindow", "Tüm Aşıları Tamamlanan Kişi Sayısı"))
        self.TAsiOlanSayiLbl.setText(_translate("MainWindow", "7.542.933"))
        self.TAsiOlanYuzdeLbl.setText(_translate("MainWindow", "Nüfus yüzdesi : %9"))
        self.TVakaYuzdeLbl.setText(_translate("MainWindow", "25 %"))
        self.TAsiYuzdeLbl.setText(_translate("MainWindow", "25 %"))
        self.TAsiOlanSayiPrgLbl.setText(_translate("MainWindow", "Toplam Aşı Olan Sayısı : 3.745.657"))
        self.TNufusuLbl_2.setText(_translate("MainWindow", "Türkiye Nüfusu : 83.614.362"))
        self.TNufusuLbl.setText(_translate("MainWindow", "Türkiye Nüfusu : 83.614.362"))
        self.TVakaPrgLbl.setText(_translate("MainWindow", "Toplam Vaka Sayısı : 3.745.657"))
        self.AAsiOlanLbl.setText(_translate("MainWindow", "Tüm Aşıları Tamamlanan Kişi Sayısı"))
        self.AAsiOlanSayiLbl.setText(_translate("MainWindow", "7.542.933"))
        self.AAsiOlanYuzdeLbl.setText(_translate("MainWindow", "Nüfus yüzdesi : %9"))
        self.AVefatLbl.setText(_translate("MainWindow", "Vefat Sayısı"))
        self.AVefatSayiLbl.setText(_translate("MainWindow", "33.454"))
        self.AVefatArtisLbl.setText(_translate("MainWindow", "Dün bildirilen vefat sayısı : + 253"))
        self.AVakaYuzdeLbl.setText(_translate("MainWindow", "25 %"))
        self.AAsiYuzdeLbl.setText(_translate("MainWindow", "25 %"))
        self.AAsiOlanSayiPrgLbl.setText(_translate("MainWindow", "Toplam Aşı Olan Sayısı : 3.745.657"))
        self.ANufusLbl.setText(_translate("MainWindow", "ABD Nüfusu : 331.002.651"))
        self.ANufusLbl_2.setText(_translate("MainWindow", "ABD Nüfusu : 331.002.651"))
        self.AToplamVakaPrgLbl.setText(_translate("MainWindow", "Toplam Vaka Sayısı : 3.745.657"))
        self.ADozLbl.setText(_translate("MainWindow", "Toplam Doz Sayısı"))
        self.ADozSayiLbl.setText(_translate("MainWindow", "18.320.384"))
        self.ADozArtisLbl.setText(_translate("MainWindow", "Dün bildirilen doz sayısı  : + 230.601"))
        self.AToplamVakaLbl.setText(_translate("MainWindow", "Toplam Vaka Sayısı "))
        self.AToplamSayiLbl.setText(_translate("MainWindow", "3.745.657"))
        self.AVakaArtisLbl.setText(_translate("MainWindow", "Dün bildirilen Vaka sayısı  : + 55.791"))
        self.copyright.setText(_translate("MainWindow", "Copyright ©  Maresal Programming"))
